name: esca_pay
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.2.3
  flutter_dynamic_icon: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: lib/assets/app_icon.png

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/
    - lib/assets/themes/default/
    - lib/assets/themes/girly/
    - lib/assets/themes/boy/
