name: esca_pay
description: "A new Flutter project."
publish_to: "none"
version: 1.0.3

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.2.3
  flutter_dynamic_icon: ^2.1.0
  flutter_local_notifications: ^16.1.0
  timezone: ^0.9.2
  flutter_timezone: ^3.0.1
  file_picker: ^5.5.0
  share_plus: ^7.1.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.0
  hive_generator: ^2.0.0

flutter_launcher_icons:
  image_path: "lib/assets/app_icon.png"
  ios: true
  android: true
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
  linux:
    generate: false
  flavor_mapping:
    default:
      image_path: "lib/assets/app_icon.png"
      ios: true
      android: true
    girly:
      image_path: "lib/assets/themes/girly/app_icon.png"
      ios: true
      android: true
    boy:
      image_path: "lib/assets/themes/boy/app_icon.png"
      ios: true
      android: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/
    - lib/assets/themes/default/
    - lib/assets/themes/girly/
    - lib/assets/themes/boy/
